name: Code check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: yarn lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
