name: Deploy
on:
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.14.3
          run_install: false

      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - run: pnpm install
      - run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
